from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any

from fastapi import FastAPI
from pydantic import BaseModel
from scipy import stats
from pptx import Presentation

ROOT_DIR = Path(__file__).resolve().parents[1]
UPLOADS_DIR = ROOT_DIR / "uploads"
UPLOADS_DIR.mkdir(exist_ok=True)

app = FastAPI(title="Survey Stats + PPT Service")


class SignificanceRequest(BaseModel):
  rows: List[Dict[str, Any]]
  questionColumns: List[str]
  groupColumn: str = "Segment"


class InsightRequest(BaseModel):
  kpis: List[Dict[str, Any]]
  significance: Dict[str, Any]


class PptRequest(BaseModel):
  title: str
  kpis: List[Dict[str, Any]]
  charts: List[Dict[str, Any]]
  insight: str


def _to_float_list(rows, question, group_column, group_name):
  values = []
  for row in rows:
    if str(row.get(group_column, "")) == str(group_name):
      try:
        values.append(float(row.get(question)))
      except (TypeError, ValueError):
        continue
  return values


@app.get("/health")
def health():
  return {"status": "ok"}


@app.post("/significance")
def significance(req: SignificanceRequest):
  groups = sorted({str(row.get(req.groupColumn, "Unknown")) for row in req.rows})
  markers = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  result = defaultdict(dict)

  for question in req.questionColumns:
    for i, group_a in enumerate(groups):
      vals_a = _to_float_list(req.rows, question, req.groupColumn, group_a)
      for j, group_b in enumerate(groups):
        if i >= j:
          continue
        vals_b = _to_float_list(req.rows, question, req.groupColumn, group_b)
        if len(vals_a) >= 2 and len(vals_b) >= 2:
          t_stat, p_value = stats.ttest_ind(vals_a, vals_b, equal_var=False)
          if p_value < 0.05:
            label = f"{markers[i]}>{markers[j]}" if sum(vals_a)/len(vals_a) > sum(vals_b)/len(vals_b) else f"{markers[j]}>{markers[i]}"
            result[question][f"{group_a}_vs_{group_b}"] = {
              "significant": True,
              "pValue": round(float(p_value), 4),
              "label": label,
            }
          else:
            result[question][f"{group_a}_vs_{group_b}"] = {"significant": False, "pValue": round(float(p_value), 4), "label": "ns"}

  return {"groupColumn": req.groupColumn, "groups": groups, "comparisons": result}


@app.post("/insight")
def insight(req: InsightRequest):
  if not req.kpis:
    return {"summary": "No KPI data available."}

  best = max(req.kpis, key=lambda x: x.get("meanScore", 0))
  improvement = round(best.get("topBox", 0) - best.get("bottomBox", 0), 2)
  text = f"{best.get('question')} leads performance with mean score {best.get('meanScore')}. Satisfaction balance improved by {improvement}% points."
  return {"summary": text}


@app.post("/generate-ppt")
def generate_ppt(req: PptRequest):
  prs = Presentation()

  title_slide = prs.slides.add_slide(prs.slide_layouts[0])
  title_slide.shapes.title.text = req.title
  title_slide.placeholders[1].text = "Auto-generated by Survey Analytics SaaS"

  kpi_slide = prs.slides.add_slide(prs.slide_layouts[1])
  kpi_slide.shapes.title.text = "KPI Summary"
  body = kpi_slide.shapes.placeholders[1].text_frame
  body.clear()
  for metric in req.kpis[:8]:
    p = body.add_paragraph()
    p.text = (
      f"{metric['question']}: Mean {metric['meanScore']}, Top-box {metric['topBox']}%, "
      f"Bottom-box {metric['bottomBox']}%, NPS {metric['nps']}"
    )

  insight_slide = prs.slides.add_slide(prs.slide_layouts[1])
  insight_slide.shapes.title.text = "Insight Summary"
  insight_slide.placeholders[1].text = req.insight

  chart_slide = prs.slides.add_slide(prs.slide_layouts[1])
  chart_slide.shapes.title.text = "Chart Highlights"
  lines = []
  for chart in req.charts[:6]:
    lines.append(f"{chart['question']} distribution: {chart['bar']['values']}")
  chart_slide.placeholders[1].text = "\n".join(lines)

  filename = f"survey-report-{datetime.now().strftime('%Y%m%d-%H%M%S')}.pptx"
  output = UPLOADS_DIR / filename
  prs.save(str(output))

  return {"filename": filename}
